volumes:
  postgres_data:

services:
  postgres:
    container_name: test_db
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432