services:
  postgres:
    deploy:
      resources:
        limits:
          memory: 512M # Hard limit. Container restart on overlimit
        reservations:
          memory: 128M # Reserved at start

  backend:
    deploy:
      resources:
        limits:
          memory: 1G # Hard limit. Container restart on overlimit
        reservations:
          memory: 256M # Reserved at start
    networks:
      - proxy-net

  caddy:
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/ci.sh:/etc/ci.sh  # test script
      - caddy-config:/config  # configuration autosaves
      - caddy-data:/data  # saving certificates
      - ~/prod-frontend/dist:/var/www/frontend  # frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy-net
    deploy:
      resources:
        limits:
          memory: 256M # Hard limit. Container restart on overlimit
        reservations:
          memory: 64M # Reserved at start

volumes:
  caddy-config:
  caddy-data:

networks:
  proxy-net: