services:
  postgres:
    image: postgres:13
    env_file: ../.env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - invatur

  backend:
    image: invatur-backend:local
    restart: unless-stopped
    build:
      context: ../.
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ../.env
    networks:
      - invatur

volumes:
  postgres_data:

networks:
  invatur:
