services:
  postgres:
    container_name: test_db
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - ./logs/:/app/logs/
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data: